### ISSUE TITLE
关于cpp依赖项安装和使用

### ISSUE THREAD

**Issue by Icemug** [luk036/ckpttn-cpp#3]
老师您好，我准备从您的开源代码入手了解电路分区算法，在构建cpp版本的项目中出现一些问题。我在Ubuntu 20.04.6 LTS 中执行了命令：cmake -S. -B build
获得以下报错：
-- CPM: adding package PackageProject.cmake@1.6.0 (v1.6.0)
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: container) (found version "1.67.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
  specific.cmake:5 (find_package)
  CMakeLists.txt:40 (include)

-- Configuring incomplete, errors occurred!
See also "/mnt/d/data/VLSIPartition/mlfm/ckpttn-cpp/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/d/data/VLSIPartition/mlfm/ckpttn-cpp/build/CMakeFiles/CMakeError.log".

此外，算法的python版本能够正确安装，在开始学习前想请问算法是否基于某论文，有没有相关使用指南，课程，或文献。任何对该算法本身的介绍都会很有帮助，感谢您的时间！

**Comment by luk036** [comment]
先安装 boost::container 库：

sudo apt install libboost-container-dev

**Comment by Icemug** [comment]
我尝试了很多方法安装boost::container 库， 也试了sudo apt install libboost-container-dev
运行apt list --installed '*boost*' 后可以找到：
libboost-container-dev/focal,now 1.71.0.0ubuntu2 amd64 [installed]
libboost-container1.71-dev/focal,now 1.71.0-6ubuntu6 amd64 [installed,automatic]
libboost-container1.71.0/focal,now 1.71.0-6ubuntu6 amd64 [installed,automatic]

不管安装的container是什么版本，他们都会导致错误
Could NOT find Boost (missing: container) (found version "1.71.0") （version）

**Comment by luk036** [comment]
安装了libboost-dev没有？

sudo apt install libboost-dev

**Comment by Icemug** [comment]
安装了，此前用的sudo apt-get install libboost-all-dev 
所用安装如下 （Ubuntu 20.04.6 LTS）
sudo apt-get update
sudo apt install git
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt install gcc-10 gcc-10-base gcc-10-doc g++-10
sudo apt install libstdc++-10-dev libstdc++-10-doc
sudo apt install build-essential
gsl: 
sudo apt-get install libgsl-dev
XNetwork: （此处安装不明，默认自动构建XNetwork）
sudo apt-get install -y python3-networkx 
boost:
sudo apt-get install libboost-all-dev
sudo apt-get install cmake libblkid-dev e2fslibs-dev libboost-all-dev libaudit-dev
sudo apt install libboost-container-dev
sudo apt install libboost-dev
报错仍存在

**Comment by luk036** [comment]
我记得boost好像是要1.72以上，早期的版本不支持cmake的FindPackage

**Comment by luk036** [comment]
试了一下没问题：

https://www.bilibili.com/video/BV1pu4y1L7nz/?share_source=copy_web&vd_source=3fbf79e74a445426f4b573d984f53f4c
